services:
  - type: web
    name: stefadore-dash
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: STEFADORE_DASHBOARD_HOST
        value: 0.0.0.0
